// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehhxdramvqjtmkrixdtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoaHhkcmFtdnFqdG1rcml4ZHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNTI5ODIsImV4cCI6MjA4ODYyODk4Mn0.7tCeR4jXYJtqc5M2ZIbpbQP72pKhXZBAJhmLZ8uXNTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});
